services:
  postgres:
    image: postgres:17-alpine
    container_name: pr-router-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  migrate:
    build: .

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    command: ["alembic", "upgrade", "head"]

  app:
    build: .

    depends_on:
      migrate:
        condition: service_completed_successfully

    env_file:
      - .env

    ports:
      - "8080:8080"

volumes:
  pg_data:
