"""add merged_at for PullRequest model

Revision ID: 7edc7dbb8cf4
Revises: 7ad9ce476444
Create Date: 2026-07-05 14:19:15.258024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edc7dbb8cf4'
down_revision: Union[str, Sequence[str], None] = '7ad9ce476444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'merged_at')
    # ### end Alembic commands ###
